### ISSUE TITLE
Overlay chatboxes inside of website tabs

### ISSUE THREAD

**Issue by stoically** [stoically/riot-webext#11]
[Proposal by forteller on reddit](https://www.reddit.com/r/firefox/comments/etfcy9/riot_as_firefox_addon_a_universal_secure_chat_app/ffgzt9f/)

> something that floats on top of any website, just like the chat boxes in Facebook stays with you no matter where on Facebook you go :)

One challenge would be that this would require host permissions for all websites, as you'd need to inject the overlay into every website; which might be not a good idea for this particular Add-on from an security-perspective. But in general this is definitely something that would be nice to have!

**Comment by forteller** [comment]
Thanks for thinking about this! Let me just cut and paste my original thoughts about this, from my old blogpost about how to make it easier for more people to rely less on Facebook:

> You know how when you start Thunderbird for the first time it asks you if you’d like to configure it to use an existing e-mail account, of if you’d like to register a new one? The browser should do the same, only with XMPP instead of e-mail. After this a small chat box will be displayed in the bottom right of your browser at all times. It will function just like Facebook’s chat box: Expand to show you your online friends when you click on it, and open new conversations in boxes to the left. It is important to find a way to get people to sign up for a Free/Open XMPP server, but since Facebook chat is based on XMPP you can get all your Facebook friends here too. This means that using this feature has great utility from the start, and that it will greatly reduce the need for many to have Facebook constantly open.
> 
> Mozilla is already working on something very similar to this, Mozilla Talkilla. It looks really nice, but so far it doesn’t let you use your existing XMPP account or help you set up a new one. It also only lets you add friends using your Google account. We need to find some solution to the problem «let people find their friends, no matter what service they are using». If not everyone will keep doing the easiest thing: Integrating their services with only Google, Facebook and a few other huge players, which means their monopolistic stranglehold will just keep growing. And that is the exact thing I want to fight with my proposal.

So yeah, this is really old and somewhat outdated. Facebook stopped using XMPP, for one. But the main thing is still really important. Matrix for the chat protocol and WebFinger or ActivityPub or something to find your friends? I'm no expert.

**Comment by forteller** [comment]
I was very much looking forward to this, and have been subscribed to updates on releases in hopes to see it implemented. But now I see it's been closed, with no comment. Does this mean it's not going to happen?

**Comment by stoically** [comment]
I still think it's a nice idea, and added it to the idea board, but given the complexity of the task it's out of scope for me personally. Might want to open an issue over in the Riot Web repo and make the suggestion, maybe they're interested?
