### ISSUE TITLE
pasting images from the clipboard doesn't work

### ISSUE THREAD

**Issue by retrotails** [stoically/riot-webext#15]
using the firefox extension in linux, pasting an image copied to the clipboard via "xclip -selection clipboard -t image/png -i $f" results in the binary data getting pasted into the text box instead of the image.
it works as expected using the electron version.

**Comment by stoically** [comment]
Unfortunately can't reproduce on my end, works as expected for me.

Which Distro are you using? Firefox or Chrome? Do you see any errors in the console (Ctrl+Shift+I -> Console) when pasting? How do you paste (I'm using Ctrl+V)?

**Comment by retrotails** [comment]
I just tried with a new firefox profile and the issue went away - apparently something browser configuration related on my end. closing.
