### ISSUE TITLE
Version 1.5.7.8 opens to blanks screen in firefox esr 68.4.2

### ISSUE THREAD

**Issue by anoduck** [stoically/riot-webext#21]
**Describe the bug**
In OpenBSD release Current, Firefox-esr (version 68.4.2esr) no longer loads riot chat. It simply opens up to a blank page whose color depends on whichever riot chat theme you run. 

**To Reproduce**
1. Run the specified version of firefox esr, 68.4.2esr.
2. Install the addon.
3. Attempt to open riot with extension.
4. If this successfully does not produce the error, then the error must be significant to OpenBSD.

**Expected behavior**
Expected it to open riot successfully as it did before the previous update. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser: Firefox ESR
 - Browser Version: 68.4.2esr
 - Riot WebExtension Version: 1.5.7.(8-9)
 - Riot WebExtension Version: 1.5.7.7 - Works!

**Additional context**
As mentioned above version 1.5.7.7 works and is currently what I have reverted to. The changes causing the current release to stop working occurred in version 1.5.7.8. This is when something went a fowl for my browser.

**Comment by stoically** [comment]
Version 1.5.7.8 dropped `unsafe-eval` as requirement in the manifest.json which broke compatibility with Firefox version <69 at the time. But 1.5.8.4 switched to bundling a stable version of riot web, which made it work again for Firefox 68 - so it basically fixed itself. v1.5.8.4 is currently in review over at AMO, so if that passes review it should start working again. Thanks for reporting and sorry for the hassle!

**Comment by anoduck** [comment]
I knew you were already on it, because you take care of business. Thanks for the response, and the extension itself. I look forward to the new release.
